name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: poetry
    - run: |
        poetry env use python3.10
        poetry install
    - name: Test with PyTest
      run: |
        export SPOTIPY_CLIENT_ID=${{ secrets.SPOTIPY_CLIENT_ID }}
        export SPOTIPY_CLIENT_SECRET=${{ secrets.SPOTIPY_CLIENT_SECRET }}
        export POETRY_SPOTIPY_CLIENT_ID=${{ secrets.POETRY_SPOTIPY_CLIENT_ID }}
        export POETRY_SPOTIPY_CLIENT_SECRET=${{ secrets.POETRY_SPOTIPY_CLIENT_SECRET }}
        poetry run pytest
    